# Generated by Django 4.2.5 on 2023-10-04 09:59

import cloudinary.models
import django.core.validators
from django.db import migrations
import videoapp.validations


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[videoapp.validations.video_size, django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='video'),
        ),
    ]
